[theme]
base = dark
primaryColor = "#123b5d"
backgroundColor = "#808c9e"
secondaryBackgroundColor = "#2467b4"
textColor = "#ffffff"
font = "sans serif"
baseFontSize = 22

[client]
toolbarMode = "viewer"
