[theme]
base = "light"
primaryColor = "#f59e0b"
backgroundColor = "#f4f7fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#102133"
grayColor = "#55657a"
font = "sans serif"
baseFontSize = 26

[client]
toolbarMode = "viewer"
